open-telemetry/opentelemetry-ebpf-instrumentation

pkg/export/debug/debug_test.go, pkg/export/otel/metrics.go, pkg/export/otel/traces.go, pkg/export/prom/prom.go, pkg/export/prom/prom_test.go, pkg/internal/request/span.go, pkg/internal/request/span_test.go, pkg/transform/routes.go, pkg/transform/routes_test.go, test/integration/configs/instrumenter-config-grpc-export.yml, test/integration/configs/instrumenter-config-no-route.yml, test/integration/configs/instrumenter-config-other-grpc.yml, test/integration/configs/instrumenter-config.yml, test/integration/k8s/manifests/06-beyla-daemonset-disable-informers.yml, test/integration/k8s/manifests/06-beyla-daemonset.yml, test/integration/red_test.go
Keeps addressing #7 .
Removing YAML configuration section `routes > ignored_patterns`:
- Its usage is confusing because it does not use regular expressions nor globs, but route matchers (same as the `patterns` sibling section). It adds yet another way to specify a pattern in our configuration.
- Its functionality is already covered by `filter > application > url_path > not_match` YAML section.
=> Remove routes > ignored_patterns configuration option

pkg/beyla/config.go, pkg/config/env_replacer.go, pkg/config/env_replacer_test.go, pkg/internal/appolly/appolly.go, pkg/kubecache/config.go, test/integration/k8s/manifests/06-beyla-external-informer.yml, test/integration/k8s/manifests/06-beyla-netolly-dropexternal.yml, test/integration/k8s/manifests/06-beyla-netolly-multizone.yml, test/integration/k8s/manifests/06-beyla-netolly.yml
Adds support for env var substitution according to the OTEL spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/data-model.md#environment-variable-substitution
Part of https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/issues/7
=> Support OTEL env var substitution in YAML config

pkg/kubecache/meta/informers.go, pkg/kubecache/meta/informers_init.go, pkg/kubecache/service/service.go
Since the Kubernetes event handler does not run with a defined order, using it to define the last status update of the stored entities was a bad Idea because they could be modified after the data is stored (and accessed e.g. for ordering).
This patch makes sure that the kubernetes entities are immutable, since the StatusTimeEpoch field is inferred from metadata before it is stored in the Informer storage.
Port of https://github.com/grafana/beyla/pull/1973
=> Fix race condition in K8s informers cache

test/integration/red_test_dotnet.go, test/tools/debug.go, test/tools/debug_test.go
`TestSuite_DotNet` test is lately flaky, and the issue seems difficult to reproduce locally. This PR just prints whatever the failed tests receive
=> Add extra debug data to flaky test

pkg/instrumenter/instrumenter.go, pkg/internal/appolly/appolly.go, pkg/internal/discover/attacher.go, pkg/internal/discover/finder.go, pkg/internal/ebpf/common/ringbuf.go, pkg/internal/ebpf/common/ringbuf_test.go, pkg/internal/ebpf/tracer.go, pkg/internal/ebpf/tracer_darwin.go, pkg/internal/ebpf/tracer_linux.go, pkg/internal/netolly/agent/agent.go, pkg/internal/pipe/instrumenter.go, pkg/internal/pipe/instrumenter_test.go, pkg/internal/traces/read_decorator.go, pkg/pipe/swarm/instancer.go, pkg/pipe/swarm/runner.go, pkg/pipe/swarm/swarm_test.go, pkg/transform/k8s.go
Sometimes, OBI gets stalled during shutdown, causing that it requires to detect that situation and self-terminate its process. But that could cause that some eBPF resources aren't properly clean).
This PR adds to the `swarm.Runner` a mechanism to auto-detect which nodes are frozen during shutdown and pointing to them, to facilitate debugging.
This PR also fixes some nodes that weren't properly finished because their input channels weren't closed nor addressed the context cancelation.
=> Node swarm zombie detector

pkg/app/request/span.go, pkg/app/request/span_test.go, pkg/components/ebpf/common/fast_cgi_detect_transform.go, pkg/components/ebpf/common/http2grpc_transform.go, pkg/components/ebpf/common/httpfltr_transform.go, pkg/components/ebpf/common/kafka_detect_transform.go, pkg/components/ebpf/common/pids.go, pkg/components/ebpf/common/pids_test.go, pkg/components/ebpf/common/redis_detect_transform.go, pkg/components/ebpf/common/spanner.go, pkg/components/ebpf/common/sql_detect_transform.go, pkg/export/debug/debug.go, pkg/export/debug/debug_test.go, pkg/export/otel/metrics.go
Beyla, which now vendors OBI, has a legacy feature to mark spans as ignored by traces and metrics. We will remove it from the next major release but for now we need an additional space to set the ignore flags on the span. This PR renames the existing Flags field on the request.Span to TraceFlags (because it was related to the w3c trace context) and introduces a new Flags field which allows Span to be tagged.
=> Add span Flags field

pkg/components/netolly/agent/pipeline.go, pkg/components/pipe/instrumenter.go, pkg/export/attributes/attr_defs.go, pkg/export/attributes/attr_selector.go, pkg/filter/attribute.go, pkg/filter/attribute_test.go
This PR makes part of the attributes code extensible so that components embedding OBI can supply their own attribute group extensions.
=> Provide means for attribute groups to be extended

pkg/beyla/config.go, pkg/components/discover/attacher.go, pkg/components/discover/finder.go, pkg/components/discover/matcher.go, pkg/components/discover/typer.go, pkg/components/discover/watcher_proc.go, pkg/components/discover/watcher_proc_test.go, pkg/components/ebpf/tracer.go, pkg/components/ebpf/tracer_linux.go, pkg/export/attributes/attr_defs.go, pkg/export/attributes/attr_selector_test.go, pkg/export/otel/metrics.go, pkg/export/otel/metrics_test.go, pkg/export/otel/pid_tracker.go, pkg/export/prom/prom.go, pkg/export/prom/prom_test.go, test/integration/docker-compose-client.yml, test/integration/docker-compose.yml, test/integration/k8s/informer_cache/k8s_informer_cache_main_test.go, test/integration/red_test.go, test/integration/traces_test.go
OBI can generate span metrics directly which enables tools that rely on span metrics to render service graphs, without having to go through traces, which if are sampled will produce unreliable data. The format that Beyla/OBI initially used was based on the original donation of Tempo span metrics generator. However, since that donation the OTel community has changed the format and this PR fixes that support. Port of https://github.com/grafana/beyla/pull/1989
Additionally, the current OBI implementation added the PID to the target_info which can significantly increase cardinality. This PR ports the fixes related to multiple PIDs per container from Beyla. Port of https://github.com/grafana/beyla/pull/1960 
Also makes host info metrics explicitly enabled. Port from …
=> New OTel span metrics format and port pid handling

test/integration/nodejs_multiproc_test.go
The test starts sending requests before the injector has had the chance to finish injecting - give it a little time.
=> [Test fix] Give enough time for the nodejs injector

bpf/.clang-tidy, bpf/generictracer/k_tracer.c, bpf/gotracer/go_nethttp.c
Enable a new class of clang-tidy diagnostics (clang-analyzer). One of the diagnostics (dead store) already pointed out a couple of places in which we were reading/writing variables that were not being used.
The `-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling` has been disabled as it implicates `__builtin_memcpy` and it's all over the place at this stage (and there's no ebpf alternative, in a regular scenario we'd replace that with `memcpy_s`).
=> Enable more clang-tidy diagnostics

pkg/export/otel/metrics.go, pkg/export/otel/traces.go, pkg/export/prom/prom.go, test/integration/configs/instrumenter-config-grpc-export.yml, test/integration/configs/instrumenter-config-no-route.yml, test/integration/configs/instrumenter-config-other-grpc.yml, test/integration/configs/instrumenter-config.yml, test/integration/k8s/manifests/06-beyla-daemonset-disable-informers.yml, test/integration/k8s/manifests/06-beyla-daemonset.yml, test/integration/red_test.go
[This previous PR](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/183) didn't really restored te ignore_routes functionality, as the metrics/traces exporters didn't make use of the flag in order to discard metrics or traces.
=> Fix ignoreMetrics and ignoreTraces flags

bpf/generictracer/iovec_len.h, bpf/generictracer/k_send_receive.h, bpf/generictracer/k_tracer.c, bpf/generictracer/maps/active_accept_args.h, bpf/generictracer/maps/active_connect_args.h, bpf/generictracer/maps/active_recv_args.h, bpf/generictracer/maps/active_send_args.h, bpf/generictracer/maps/active_send_sock_args.h, bpf/generictracer/maps/connection_meta_mem.h, bpf/generictracer/maps/grpc_frames_ctx_mem.h, bpf/generictracer/maps/http2_info_mem.h, bpf/generictracer/maps/http_info_mem.h, bpf/generictracer/maps/iovec_mem.h, bpf/generictracer/maps/ongoing_http2_connections.h, bpf/generictracer/maps/ongoing_http2_grpc.h, bpf/generictracer/maps/ongoing_tcp_req.h, bpf/generictracer/maps/pid_tid_to_conn.h, bpf/generictracer/maps/protocol_args_mem.h, bpf/generictracer/maps/ssl_to_pid_tid.h, bpf/generictracer/maps/tcp_connection_map.h, bpf/generictracer/maps/tcp_req_mem.h, bpf/generictracer/maps/upstream_init_args.h, bpf/generictracer/nginx.c, bpf/generictracer/protocol_common.h, bpf/generictracer/protocol_http.h, bpf/generictracer/protocol_http2.h, bpf/generictracer/protocol_tcp.h, bpf/generictracer/ssl_defs.h, bpf/generictracer/types/grpc_frames_ctx.h, bpf/generictracer/types/http2_conn_info_data.h
This is a follow up of https://github.com/grafana/beyla/pull/1791 - see that PR's decription for context.
There's still plenty to do and other PRs will follow from time to time.
The present PR solely targets the maps in `generictracer`.
=> Reorganise ebpf file structure - part II

pkg/components/discover/watcher_kube.go, pkg/components/discover/watcher_kube_test.go, test/integration/red_test_dotnet.go
OBI can match processes by various attributes, namely, they can be matched by their "process" attributes, such as executable name or ports they open. OBI can also match processes by extended attributes in certain environments like Kubernetes, for example a Kubernetes namespace.
To perform the matching of these extended attributes, like Kubernetes metadata attributes, we must match the process information (the process ID - PID) to the Kubernetes pod metadata. To make things more complicated, the pod metadata may not be present at the time we discover the process, which means we'll discover a process, discard it based on the existing selection criteria, but then we need to report it as found again once we get Kubernetes metadata for it, so that we can match it by the Kubernetes selection …
=> Ensure we support more than one pid per container, in pids to pods

pkg/components/ebpf/common/ringbuf_test.go, pkg/export/otel/metrics.go
We pre-create target info so that we can write the process as instrumented even before any traffic is seen by the BPF side. The target info was created but without a description label, which can cause this annoying message in debug OTel collector export logs:
```
collected metric target_info label:{name:"host_id"  value:"d8dc7712-a82d-4108-bb2c-9d1d39d4915e"}  label:{name:"host_name"  value:"beyla"}  label:{name:"instance"  value:"beyla:133937"}  label:{name:"job"  value:"integration-test/service-r"}  label:{name:"os_type"  value:"linux"}  label:{name:"service_instance_id"  value:"beyla:133937"}  label:{name:"service_name"  value:"service-r"}  label:{name:"service_namespace"  value:"integration-test"}  label:{name:"telemetry_sdk_language"  value:"nodejs"}  label:{name:"telemetry_sdk_name" …
```
=> Ensure target info has the correct description

pkg/components/ebpf/common/pids.go, pkg/components/ebpf/common/pids_test.go, pkg/components/svc/svc.go, pkg/export/otel/metrics.go, pkg/export/otel/metrics_test.go, pkg/export/prom/prom.go, pkg/export/prom/prom_test.go, pkg/services/criteria.go
OBI can detect that a service that has been defined to be instrumented is already instrumented with the OTel SDK, e.g. it's exporting actively it's own traces, metrics or both. We have this option on by default.
However, OBI can also directly produce span and service graph metrics. In this case we would duplicate metrics if a service is exporting traces and the end user has configured the OTel collector span/graph metrics processor. This PR adds an option to disable the generation of the span/service graph metrics, for OTel instrumented services, if the user environment has the span/service graph processor enabled in their Collector.
=> Span metrics export filtering with a separate flag

bpf/common/scratch_mem.h, bpf/generictracer/ebpf_ipc.h, bpf/generictracer/k_tracer.c, bpf/generictracer/k_tracer_defs.h
The original codepath of the ebpf IPC buffers/`handle_ebpf_ipc` could not deal with a corner case in which the originating buffer was coming from a kernel bvec - bvecs represent physical pages that cannot be mapped into the eBPF memory space, and therefore cannot be read.
Because the eBPF IPC payloads are very small (currently 20 bytes), sometimes the kernel is able to detect that they are being sent to a destination inside the same host, and instead of copying the payload, it just shares the memory pages with the receiving end, thus yielding a bvec.
When that happens, we cannot read the IPC payload, and the trace context propagation breaks.
This PR relies on the already implemented fallback mechanisms (such as buffer setup by the http filter program) to defeat this limitation.
=> Fix reading the eBPF IPC buffers

pkg/beyla/config.go, pkg/beyla/config_test.go, pkg/components/discover/matcher_test.go, pkg/services/attr_glob.go, pkg/services/attr_regex.go, pkg/services/criteria.go, pkg/services/criteria_test.go
This introduces a breaking change at API level: `services.NewGlob` and `services.NewPathRegexp` now receive directly a string (they were always invoked with `regexp/glob.MustCompile` as they are just internal utility functions).
Also `services.NewPathRegexp` has been renamed to `NewRegexp` for coherence.
=> Add YAML marshaller for services.GlobAttr, PortEnum and RegexpAttr

.gitignore, pkg/export/otel/metrics.go, pkg/export/prom/prom.go, test/integration/red_test.go
We are missing "_seconds" for the Prometheus side for the new OTel Span metrics format.
=> Fix Prometheus export span metric name

README.md
I know that **OBI** term is commonly used by OTel Go Auto-Instrumentation SIG.
I think we should document this term for transparency.
CC @open-telemetry/go-instrumentation-maintainers
=> docs: define the OBI abbreviation

bpf/netolly/flows_sock.c, pkg/components/netolly/ebpf/sock_tracer.go
If you run together netolly and appolly, you will see 2 EBPF programs with the same name `beyla_socket__http_filter`.  This is not ideal if you want to debug/benchmark EBPF programs. Moreover, this is not an HTTP-specific code, so it could make sense to change its name.
=> cleanup: rename socket filter prog in netolly

pkg/components/ebpf/generictracer/generictracer.go
This PR changes which kernel symbol is used to monitor TCP message sending from `tcp_sendmsg_locked` to `tcp_sendmsg`.
After pairing with @grcevski, we found that the use of `tcp_sendmsg_locked` was incompatible with the orbstack kernel `6.14.10-orbstack-00291-g1b252bd3edea`, even though `tcp_sendmsg_locked` was found to be present in `/proc/kallsyms`.
It could be that the use of `sock_*` BPF programs are changing the kernel execution path, which might cause the `tcp_sendmsg_locked()` function to never be called.
The `tcp_sendmsg_locked` symbol is also known to not always be available on certain kernel configurations.
=> fix: use tcp_sendmsg instead of tcp_sendmsg_locked

pkg/export/prom/prom.go, pkg/export/prom/prom_test.go
Add sanitization step in Prometheus metric generation to avoid make OBI panic when a label with invalid UTF8 is present. 
Fixes https://github.com/grafana/beyla/issues/1867
=> Fix panic due invalid UTF-8 labels

bpf/gotracer/go_nethttp.c
In some setups, the go_tracer.c file failed to load due to a verification error.
I don't know why but this (initially unrelated) change fixed it locally.
The uprobe/ServeHTTP_ret probe in go_nethttp.c  is unnecessarily defined twice.
* As [serve_http_returns](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/blob/main/bpf/gotracer/go_nethttp.c#L397-L398)
* As [beyla_uprobe_ServeHTTPReturns](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/blob/main/bpf/gotracer/go_nethttp.c#L397-L398)
The same probe was defined and loaded twice in the generated bpf_arm_bpfel...go , but only p.bpfObjects.BeylaUprobeServeHTTPReturns was explicitly used in gotracer.go.
=> Fix BPF load error

cmd/ebpf-instrument/main.go, pkg/beyla/config.go, pkg/components/ebpf/tcmanager/tcmanager.go, pkg/config/ebpf_tracer.go, pkg/export/otel/common.go, pkg/export/otel/metrics.go, pkg/export/otel/traces.go, pkg/services/attr_regex.go
this is very helpful when debugging, looking at the config.yaml + environment variable can be confusing and misleading.
so logging this out can help
example log:
``` 
time=2025-07-10T16:50:37.591+03:00 level=DEBUG msg="Running OpenTelemetry eBPF Instrumentation with configuration" config="{EBPF:{BpfDebug:true WakeupLen:1 BatchLength:100 BatchTimeout:1s TrackRequestHeaders:true HTTPRequestTimeout:0s ContextPropagationEnabled:true ContextPropagation:0 OverrideBPFLoopEnabled:false TCBackend:3 DisableBlackBoxCP:false HighRequestVolume:false HeuristicSQLDetect:false InstrumentGPU:false ProtocolDebug:false UseOTelSDKForJava:false RedisDBCache:{Enabled:false MaxSize:1000} BufferSizes:{MySQL:1024}} NetworkFlows:{Enable:false Source:socket_filter AgentIP: AgentIPIface:external AgentIPType:any …
```
=> log out configuration in debug mode

pkg/components/ebpf/tracer_linux.go
Apparently on new kernels, when we cannot use `bpf_probe_write_user` we get the following error message: `cannot use helper bpf_probe_write_user` instead of `unknown func bpf_probe_write_user`.
Closes #313
=> Look for the alternative lockdown error message 

Makefile
If there are no docker containers or images the `docker rm` and `docker rmi` commands become syntactically invalid. Only run the commands if there are containers or images to remove.
For example: https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/actions/runs/16375613470/job/46278493579?pr=330
=> Do not fail cleanup when empty

pkg/components/discover/attacher.go
We never closed the ELF file opened during binary file inspection, which can cause for a large number of files to remain opened when OBI is running. This can especially become a problem for short lived binaries that we keep on detecting, instrumenting etc.
=> Close the elf file when attacher is done with it

bpf/common/common.h, bpf/common/sql.h, bpf/generictracer/k_tracer.c, bpf/generictracer/k_tracer_tailcall.h, bpf/generictracer/protocol_mysql.h, bpf/generictracer/protocol_tcp.h, pkg/components/ebpf/common/common.go, pkg/components/ebpf/common/tcp_detect_transform.go, pkg/components/ebpf/common/tcp_large_buffer.go, pkg/components/ebpf/common/tcp_large_buffer_test.go, pkg/components/ebpf/generictracer/generictracer.go, pkg/config/ebpf_tracer.go
- Add large buffer `action`: init/append
- Remove mysql tail call program: it was essentially useless
- Add more sanity checks and better header parsing based on payload lengths
- Add large buffers userspace rwlock, add tests for different actions
=> bpf: implement large buffer action, improve mysql protocol inference

.github/workflows/markdown-fail-fast.yml
Copied from https://github.com/open-telemetry/opentelemetry-go/pull/7057
> The [recent fix for the markdown-fail-fast action](https://github.com/open-telemetry/opentelemetry-go/pull/7045) fixed the action for PRs, but [pushes to `main` are failing](https://github.com/open-telemetry/opentelemetry-go/actions/runs/16420891372/job/46398868230).
> 
> This fixes the action to run on pushes to main.
> 
> - Match markdown files using action `on` syntax to skip unneeded runs
> - Parse event type in script
> - Handle push event types in script
Resolve #343
=> Fix markdown-fail-fast CI on push events

bpf/generictracer/nodejs.c, pkg/components/ebpf/generictracer/generictracer.go, pkg/components/nodejs/injector.go, pkg/components/nodejs/nodejs.go
This PR brings a few fixes and enhancements to the NodeJS injector:
1. rework the code that deals with the injector protocol: all operations are now done synchronous, and most importantly, **there's no longer the need to write an intermediate file to the target container filesystem** - the script is directly injected via the socket
2. injecting the script now happens in "real time" (big quotes here), meaning that it's much faster
3. newer node versions dynamically link against `libuv.so` - so added a missing probe there
4. small ebpf debug fix
5. deleted heaps of code!
_This PR is best reviewed on a per-commit basis_
=> Overhaul NodeJS injector

pkg/components/ebpf/common/mongo_detect_transform.go
some mongo clients run `atlasVersion` command to check mongo version, this command should be ignored since its not interesting
=> ignore atlasVersion command for mongo operation

pkg/export/attributes/env.go, pkg/export/attributes/env_test.go
We noticed that `ParseOTELResourceVariable` was figuring out in a few profiles, as a consequence of `genSplit()` calls:
I went on to benchmark `ParseOTELResourceVariable` and because it allocates intermediate arrays, there's quite a bit happening there:
```
flat  flat%   sum%        cum   cum%
1480.56MB 99.76% 99.76%  1480.56MB 99.76%  strings.genSplit
0     0% 99.76%  1480.06MB 99.73%  go.opentelemetry.io/obi/pkg/export/attributes.BenchmarkParseOTELResourceVariable
0     0% 99.76%  1480.06MB 99.73%  go.opentelemetry.io/obi/pkg/export/attributes.ParseOTELResourceVariable
0     0% 99.76%   502.03MB 33.83%  strings.Split (inline)
0     0% 99.76%   978.53MB 65.94%  strings.SplitN (inline)
0     0% 99.76%  1480.06MB 99.73%  testing.(*B).launch
0     0% 99.76%  1480.06MB 99.73% …
```
=> Implement zero-alloc otel var parsing

pkg/export/otel/metrics_net.go, pkg/export/otel/metrics_net_test.go, test/integration/k8s/netolly/k8s_netolly_network_metrics.go
Network flows in OTel export mode have fake fixed resource attributes, which causes two problems:
1. It creates an entry in target info called obi-network-flows which makes no sense to the end users.
2. It creates a unique UUID each time OBI is launched, so technically it creates extra dimension in the metric which doesn't give any extra information and cannot uniquely identify the OBI instance.
Prometheus export doesn't have this problem. The Prometheus metrics for network contain the extra attributes, however since there's no getter for them in record_getters.go, I think it has no actual effect.
Open question: In case we are not running on Kubernetes, e.g. we query and we say Kube is disabled, should we have a better default network metrics config, for example, one that enables …
=> Remove resource attributes for network flows

.github/workflows/ghcr_publish_testing_images.yml
The new created images are referenced from the documentation examples, for quick test of services in some languages.
In addition, we can replace some integration tests with their prebuilt versions, and speed up them.
=> Add few more prebuilt test images

pkg/kubecache/envtest/integration_test.go, pkg/kubecache/meta/informers_init.go, pkg/kubecache/meta/informers_init_test.go
The criteria used to filtering out POD events is not sufficient, causing it to filter out important POD events such as when the POD container changes.
It also prevents users from instrumenting headless services, a decision that should potentially be asserted via configuration, rather than hardcoded.
This fixes an important and silent bug which prevents OBI from instrumenting services that have been killed/restarted but end up in a different container (but same pod).
=> Don't filter out pod update events

Makefile
We renamed the package to `go.opentelemetry.io/obi` but we forgot to update `BUILDINFO_PKG` in the Makefile.
That makes that build version and revision in internal metrics is set to `unset`.
Fixes https://github.com/grafana/beyla/issues/2117
=> Fix build info for internal metrics

bpf/common/strings.h, bpf/generictracer/http2_grpc.h, bpf/generictracer/nodejs.c
Unlike the memcpy built in, __builtin_memcmp will not be expanded into a stream of instructions for all versions of Clang. Sometimes it requires -O2 and some compilers always leave the memcmp call, which cannot be loaded by the verfiier.
This PR changes the nodejs code to use the helper we already had for grpc and extracts that helper in common.
=> Don't use memcmp directly in nodejs code

pkg/components/ebpf/gpuevent/gpuevent.go, pkg/export/prom/prom.go
There are two separate issues with our CUDA kernel launch monitoring:
1. We recently changed all kprobes related code to share the same PID filter, the common PID filter, but the GPU/CUDA monitoring isn't tested because we don't have NVIDIA runners. The change to use the correct PID filter exposed a bug in the CUDA event creation that we weren't populating the PID info, so the filter can correctly remove unnecessary events. This is the first fix.
2. There were 2 series attributes (grid size and block size) which were missing to be included in the prometheus constructor.
=> Fix missing pid info and prometheus collections

bpf/.clang-tidy, bpf/generictracer/k_tracer.c, bpf/generictracer/k_unix_sock.h, bpf/generictracer/libssl.c, bpf/generictracer/nginx.c, bpf/generictracer/nodejs.c, bpf/generictracer/protocol_common.h, bpf/generictracer/protocol_http.h, bpf/generictracer/protocol_http2.h, bpf/generictracer/protocol_postgres.h, bpf/generictracer/protocol_tcp.h, bpf/gotracer/go_nethttp.c, bpf/gpuevent/gpuevent.c, bpf/rdns/rdns_xdp.c, bpf/tctracer/tc_ip.h, bpf/tctracer/tctracer.c
Ensure clang-tidy notifies us of unused parameters. This requires us to explicitly note unused parameters that cannot be removed (such as kprobe signatures), but it also caught a few instances in which such parameters should no longer be there. It also uncovered a few other warnings that were being shadowed.
On a follow up PR I intend to enable `-Werror -Wunused-parameter` - I am not doing this now because a bunch of those are passed to `bpf_dbg_printk`, which expands to nothing on  non-debug builds, causing a few parameters to only be unused in a few instances (e.g. they need to be tagged with `[[maybe_unused]]`).
=> Enable misc-unused-parameters checks

pkg/components/pipe/instrumenter.go, pkg/export/otel/metrics_svc_graph.go, pkg/export/otel/metrics_svc_graph_test.go
This PR removes some unnecessary code that was left in metrics_svc_graph.go during a past refactor.
=> cleanup metrics_svc_graph.go

pkg/components/discover/typer.go, pkg/components/svc/svc.go, pkg/services/attr_glob.go, pkg/services/attr_regex.go, pkg/services/criteria.go, pkg/services/export.go, pkg/services/export_test.go
`ExportModes.CanExportMetrics` is invoked for each Span. I slightly optimized it by changing its internal representation by a bits map.
Now, instead of having to iterate a short slice and perform 1-2 string comparisons for each span, it just checks a bit in an integer.
The YAML marshaling/unmarshaling remained the same, as well as the rest of the public API.
=> Optimize ExportModes

pkg/components/ebpf/common/pids.go, pkg/export/otel/idgen/id_generator.go, pkg/export/otel/traces.go, pkg/export/otel/traces_gen.go, pkg/export/otel/traces_test.go, pkg/export/otel/tracesgen/tracesgen.go
Recent configuration refactoring made certain functions in the traces exporter private which breaks embedding OBI into collectors. I've now split the code that's reusable for embedding into a separate package to avoid this happening again.
=> Revert change that breaks collector embedding

pkg/components/discover/typer.go, pkg/components/svc/svc.go, pkg/services/attr_glob.go, pkg/services/attr_regex.go, pkg/services/criteria.go, pkg/services/export.go, pkg/services/export_test.go
Slightly improves the [previous PR](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/402) that already optimized ExportModes w.r.t. using slices:
This PR removes all the pointer semantics and uses ExportModes as a value:
- We don't need null checks to stay safe against null pointers.
- We save some indirections, as we are using a value.
This PR inverts the internal representation of the export list, but its public API remains the same.
Also, some places where `ExportModes` fields were defined as pointers, now become values.
In addition, we add extra code comments for a better understanding of the API and the internal implementation.
=> Few extra improvements in ExportModes

pkg/components/transform/route/clusterurl/cluster.go, pkg/components/transform/route/clusterurl/cluster_test.go, pkg/components/transform/route/clusterurl/config.go
Adds a lookup table for performance reasons.
Benchmark results over 60s:
```
> table lookup
BenchmarkClusterURLWithoutCache-20      21180284              3417 ns/op            2000 B/op         59 allocs/op
> loop 
BenchmarkClusterURLWithoutCache-20      20406266              3387 ns/op            2000 B/op         59 allocs/op
> OR chain
BenchmarkClusterURLWithoutCache-20      21681082              3326 ns/op            2000 B/op         59 allocs/op
```
=> [Route Classifier] Remove additional valid chars config option

pkg/export/otel/metrics.go, pkg/export/otel/metrics_internal.go, pkg/export/otel/metrics_test.go, pkg/export/otel/pid_tracker.go, pkg/export/otel/pid_tracker_test.go, pkg/export/prom/prom.go, pkg/export/prom/prom_test.go
- The metric `traces_host_info` metric should only be emitted for application hosts (i.e. hosts that emit traces).
- This was the case for the prometheus exporter, but not for OTEL.
- Fixes an issue where once the host info metric was initialized, it was never expired (even though it is wrapped in an `Expirer`) due to the fact that expirers only remove outdated entries as part of the process of recording new ones. Since the host won't go away (as opposed to service instances), the metric will always be recorded on every processed span.
- Fixes https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/issues/283
=> Initialize host info metric on first span

pkg/config/env_replacer.go, pkg/config/env_replacer_test.go, pkg/export/otel/otelcfg/common.go, pkg/export/otel/otelcfg/common_test.go
We support OTEL env variable replacement but we don't have support for variables
of the format $(var), which is how OpenTelemetry Operator works.
Fixes https://github.com/grafana/beyla/issues/1856
=> Fix env var substitution for OpenTelemetry Operator

test/integration/traces_test.go
After checking logs of a case that tests fails yesterday with @grcevski, we found that traces
are propagating properly. In some cases we might expect traces a bit later than usually so 
we should use `test.Eventually` to wait until the trace is in jaeger.
=> Use `test.Eventually` to try fix flaky Nested_traces_with_kprobes test

pkg/components/ebpf/common/sql_detect_postgres.go, pkg/export/otel/tracesgen/tracesgen.go
This log can happen when the full buffer is truncated and the msg iterator stops earlier than expected:
```
if len(it.buf) < int(payloadSize) {
it.err = fmt.Errorf("remaining buffer too short for message data: expected %d bytes, got %d", payloadSize, len(it.buf))
return
}
```
so in practice it happens often with default settings.
Decrease the log level to debug as the handler will just fallback
=> postgres: decrease log level to debug

debug.Dockerfile
Provides a `debug.Dockerfile` that would allow remote debugging, for example in Kubernetes clusters. To use it:
Build the image normally, and push it to your repository or to your cluster:
```bash
docker build -f debug.Dockerfile -t my/obi:dev .
kind load docker-image my/obi:dev
```
In your kubernetes deployment, use the built image and make the `2345` port available for the OBI:
```yaml
- name: obi
image: my/obi:dev
ports:
- containerPort: 2345
hostPort: 2345
name: delve
```
Port-forward your OBI container port 2345:
```bash
k port-forward obi-3dzq 2345
```
Connect delve to your `localhost:2345` connection and start debugging.
Some IDEs (e.g. Jetbrains) seamessly can connect to your debug pod:
=> Delve-enabled debug dockerfile

pkg/components/pipe/instrumenter.go, pkg/export/otel/otelcfg/config_metrics.go, pkg/export/prom/prom.go, pkg/obi/config.go, pkg/obi/config_test.go, pkg/transform/ips_filter.go, pkg/transform/ips_filter_test.go, test/integration/docker-compose.yml
This property was defined in both OTEL and Prometheus metrics section but actually only the OTEL definition was used.
Since this is a global attribute, independent from the exporter, I have moved it to the attributes section and renamed it to `drop_metric_unresolved_ips`
=> Move drop_unresolved_ips configuration to the attributes section

.github/workflows/pull_request_integration_tests.yml
Increase shard timeouts:
- Increase go test timeout to `25m`
- Increase GitHub step timeout-minutes to `30`
=> ci: increase integration test shard timeout

test/integration/traces_test.go
The flaky multiprocess test first gets all the traces containing all the `GET /dist` spans, but later checks for the internal spans, which might not be populated yet when the Jaeger client retrieves the first set of traces.
This PR puts the whole process in an `Eventually` clause, meaning that if e.g. the `GET /jtrace` span is not found, instead of failing the test, we retrieve again all the traces, expecting that the next time they might be correctly populated with all the inner spans.
=> Fix flaky multiprocess test

.github/workflows/pull_request_integration_tests.yml
Apparently, codecov supports automatically merging reports:
- https://docs.codecov.com/docs/merging-reports
So this should be as easy as each integration test shard uploading it's own coverage report to the same tag.
=> chore(ci): restore coverage reports for integration tests

pkg/components/appolly/appolly.go, pkg/components/netolly/flow/decorator_test.go, pkg/pipe/msg/queue.go, pkg/pipe/msg/queue_test.go
As long as the pipeline in `instrumenter.go` is growing, we have found some cases where the data stopped flowing across the internal queues.
In complex scenarios where queues are forked to different nodes which could either bypass or subscribe to the original queue, some race condition caused that messages were never delivered.
Current version of the pipeline works correctly, but future changes and addition could manifest again this behavior, and they are somewhat difficult to diagnose.
This PR fixes the race conditions but also adds more flexibility to the queue mechanism:
* To simplify, all the queues without subscriptors become non-blocking. We just have to make sure that each `subscribe()` method is invoked during the swarm instancing.
* Now we allow both bypassing and subscribing to …
=> Fix Queue mechanism

pkg/obi/config.go, pkg/obi/config_test.go
If the value is `0`, the handler will crash
=> kafka: set default topic uuid-to-name cache size

pkg/export/debug/debug.go, pkg/export/otel/traces.go, pkg/filter/attribute.go, pkg/transform/ips_filter.go, pkg/transform/k8s.go, pkg/transform/name_resolver.go
There was a flaky unit test that successfully evaluated the behavioral assertions, but often got stuck at the last `<-done` verification (just verifying that the pipeline stopped on context cancellation).
There were still some nodes that did not properly handled the context cancellation and could make Beyla container destruction take longer than really required.
=> Fix some nodes not properly stopping

pkg/export/otel/metrics.go, pkg/export/otel/metrics_svc_graph.go
_This PR is best reviewed on a per commit basis_
Explicitly add job and instance attributes when generating `target_info`, to ensure the OTEL SDK does not duplicate the `target_info` series with the implicitly added `job` and `instance` attributes. Apart from preventing duplicates, this ensures the metrics are correctly expired.
Bonus: some cleanup.
=> Explicitly add job and instance to target_info

pkg/components/discover/attacher.go, pkg/components/transform/route/harvest/harvester.go, pkg/services/criteria.go, test/oats/http/configs/instrumenter-config-traces-routes-disabled.yml, test/oats/http/docker-compose-java-routes-disabled.yml, test/oats/http/yaml/oats_java_routes_disabled.yaml
We recently added a feature to harvest routes from processes, Java being the only one implemented for now. However, we might encounter an issue perhaps in the field with this new feature, so I'm providing a way for customers to disable specific harvesters.
=> Add option to disable certain route harvesters

test/integration/configs/otelcol-config-4017.yml, test/integration/configs/otelcol-config.yml
The neto11y tests are generating more metrics, which are causing the collector ingest to overflow and reject them.
=> Increase grpc max recv size

pkg/components/transform/route/clusterurl/cluster.go, pkg/components/transform/route/clusterurl/cluster_test.go
Investigating the following error:
```
panic: runtime error: index out of range [9] with length 9
```
After fixing the panic, I found some of the existing test cases to be inconsistent, and added some missing test cases for `ClusterURL`. Discussed with @grcevski and agreed to update the existing test cases to focus on consistency.
TL;DR The `p` slice was shrunk to strip characters, then access was attempted on an index that no longer existed.
=> fix: panic in clusterurl

bpf/bpfcore/bpf_builtins.h, bpf/common/http_types.h, bpf/common/trace_common.h, bpf/generictracer/k_tracer_tailcall.h, bpf/generictracer/protocol_http.h, bpf/maps/sock_dir.h, pkg/components/ebpf/common/common.go, pkg/components/ebpf/generictracer/generictracer.go, pkg/components/ebpf/instrumenter.go, pkg/components/ebpf/tcmanager/tcmanager.go, pkg/components/kube/informer_provider.go, pkg/kubecache/meta/informers_init.go, pkg/obi/config.go, test/integration/multiprocess_test.go, test/integration/red_test_nodeclient.go, test/integration/red_test_rust.go, test/integration/suites_test.go, test/integration/traces_test.go
- Based on runtime kernel, load either a bpf_loop-enabled tail call or a bounded loop tail call*
- Continue with ebpf collection loading if sockops load fails
*I couldn't make this decision in a single program via BTF at runtime because of a possible loader bug. Loading an unused subprog with static linkage:
```
int prog(...) {
...
if (bpf_core_enum_value_exists(enum bpf_func_id, BPF_FUNC_loop)) {
res = myfunc();
} else {
res = myfunc__legacy();
}
...
}
static int culprit(u32 index, void *data) {
...
}
static __always_inline int myfunc() {
struct callback_ctx data = {.buf = buf, .pos = 0};
bpf_loop(nr_loops, culprit, &data, 0);
return 0;
}
static __always_inline int myfunc__legacy() {
...
return 0;
}
```
would make func_info from .BTF.ext inconsistent:
```
field ObiProtocolHttp: program …
```
=> bpf: fallback to bounded loop if bpf_loop is not available

pkg/app/request/metric_attributes.go, pkg/app/request/span_getters.go, pkg/app/request/span_getters_providers.go, pkg/app/request/span_getters_unresolved.go, pkg/app/request/span_getters_unresolved_test.go, pkg/components/ebpf/generictracer/generictracer.go, pkg/components/pipe/instrumenter.go, pkg/components/pipe/instrumenter_test.go, pkg/export/otel/expirer_test.go, pkg/export/otel/metrics.go, pkg/export/otel/metrics_svc_graph.go, pkg/export/otel/metrics_svc_graph_test.go, pkg/export/otel/metrics_test.go, pkg/export/prom/prom.go, pkg/export/prom/prom_test.go, pkg/filter/attribute_test.go, pkg/obi/config.go, pkg/obi/config_test.go, pkg/transform/name_resolver.go, pkg/transform/name_resolver_test.go, test/integration/components/pythongrpc/Dockerfile, test/integration/components/pythongrpc/main.py, test/oats/http/docker-compose-beyla-python-unresolved.yml, test/oats/http/yaml/oats_python_outgoing_host.yaml, test/oats/http/yaml/oats_python_outgoing_unresolved.yaml
To avoid cardinality explosion we had implemented a catch all "unresolved" for any IP target found for service graph metrics. However, there were some edge cases where this might not work properly.
1. This "unresolved" service is a single node without a namespace. This means that any tool that wants to print a service graph would essentially have edges to this one "singular" node, making the service graphs hard to interpret. For example, all incoming web traffic to a service will be the "unresolved" node, but also all outgoing cloud services will point to the same now "incoming" node.
2. The Prometheus export was not using the new attribute helpers, so the cardinality fixes didn't fix Prometheus metric exports. I've modified the code now to use the attributes instead of hardcoded …
=> Better unresolved span metrics

pkg/export/prom/prom_test.go, pkg/transform/name_resolver_test.go, test/integration/nodejs_multiproc_test.go
1) Fix race condition in TestAppMetricsExpiration ([link](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/actions/runs/18015439957/job/51259046190?pr=542#step:4:1208)):
```
==================
WARNING: DATA RACE
Write at 0x00c0001186c0 by goroutine 4555:
go.opentelemetry.io/obi/pkg/export/prom.TestAppMetricsExpiration.func2()
/home/runner/work/opentelemetry-ebpf-instrumentation/opentelemetry-ebpf-instrumentation/pkg/export/prom/prom_test.go:152 +0x79
github.com/mariomac/guara/pkg/test.Eventually.func1.1()
/home/runner/go/pkg/mod/github.com/mariomac/guara@v0.0.0-20250408105519-1e4dbdfb7136/pkg/test/eventually.go:57 +0x90
Previous read at 0x00c0001186c0 by goroutine 79:
go.opentelemetry.io/obi/pkg/export/prom.TestAppMetricsExpiration() …
```
=> fix: race condition in TestAppMetricsExpiration

.github/workflows/pull_request_integration_tests.yml, .github/workflows/pull_request_k8s_integration_tests.yml, Makefile, scripts/generate-integration-matrix.sh, scripts/generate-k8s-matrix.sh, test/integration/k8s/restrict_local_node/restrict_local_node_main_test.go
This PR builds on:
- #535
To reduce the CI execution time for the k8s integration tests, a different approach was required from the existing integration test sharding:
1. Shard per Kind cluster (instead of evenly distributing tests using multiple Kind clusters across various shards)
- Improved process isolation
- Faster test execution
- Avoids cluster name and host port conflicts
- Lower disk space usage per shard
2. Use `gotestsum` to make CI action logs easier to read
3. Also fixed coverage reporting for both k8s and non-k8s integration tests
Overall k8s integration execution time went down **from 45m to 10m**:
Apparently, GitHub looks in the main branch for reusable workflow files. This is no longer applicable to this PR. I removed the shared workflow I was developing for the k8s and …
=> ci: shard k8s integration tests

pkg/obi/network_cfg.go
I merged by mistake this PR https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/722 without realizing this added a breaking change. Sorry, my fault.
I think we need to discuss further the functionality implications for existing users before making the merge effective.
=> Disabling network sampling again

pkg/export/prom/prom_bpf.go
In order to enable BPF internal metrics with Prometheus, one needs to specify the "ebpf" feature explicitly in the config, i.e.
```
func promMetricsEnabled(cfg *PrometheusConfig) bool {
return cfg.EndpointEnabled() && cfg.EBPFEnabled()
}
```
However, that can be bypassed by the following condition
```
_, ok := internalMetrics.(imetrics.NoopReporter); ok || internalMetrics == nil
```
as the internal metrics reporter is neither 'Noop' nor 'nil.
This also causes issues because even when `OTEL_EBPF_INTERNAL_METRICS_EXPORTER=disabled`, an internal reporter is created if a prometheus endpoint is set.
This PR conditions enabling these ebpf metrics either by enabling prometheus or otel metrics.
=> Fix disabling BPF internal metrics

pkg/components/netolly/agent/pipeline.go, pkg/components/netolly/ebpf/sock_tracer_nolinux.go, pkg/components/netolly/ebpf/tracer_nonlinux.go, pkg/components/pipe/global/context.go
Analogously to the `OverrideAppExportChannel` option in the context info, we are providing an analogous queue to allow providing more network data exporters.
=> Allow overriding Network Export channel

pkg/components/ebpf/common/sql_detect_postgres.go
reduce postgres verbosity
```
2025-10-01 17:31:43.727	
time=2025-10-01T21:31:43.727Z level=WARN msg="Postgres response too short"
```
similar to https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/605 for mysql
=> fix postgres error verbosity
