CHANGELOG.md
=> Add project changelog

.github/workflows/check_gh_actions_security.yml, .github/workflows/clang-format-check.yml, .github/workflows/clang-tidy-check.yml, .github/workflows/publish_dockerhub_main.yml, .github/workflows/pull_request.yml, .github/workflows/pull_request_check_license.yml, .github/workflows/pull_request_integration_tests.yml, .github/workflows/pull_request_integration_tests_arm.yml, .github/workflows/pull_request_integration_tests_vm_5.15_x86_64.yml, .github/workflows/pull_request_integration_tests_vm_6.10_x86_64.yml, .github/workflows/pull_request_k8s_integration_tests.yml, .github/workflows/pull_request_oats_test.yml, .github/workflows/update-offsets.yml, .github/workflows/workflow_integration_tests_vm.yml
Ran [zizmor](https://github.com/woodruffw/zizmor) for each workflow file and fixed several complaints about potential security issues
=> Enhance security of github actions

.github/workflows/publish_dockerhub_main.yml
Based on [this](https://github.com/open-telemetry/community/issues/2709#issuecomment-2881034052) feedback.
=> Add package write permision to Docker publish workflow

.github/workflows/update-offsets.yml
Fix #49 
Use the OTel bot as the author, committer, and signer.
https://github.com/open-telemetry/community/blob/main/assets.md#otelbot
=> Fix offsets update workflow

.github/workflows/update-offsets.yml
Fix #49 
Follow-up to #55 
Update to the latest version so we can sign commits.
=> Bump peter-evans/create-pull-request action to v7.0.8

.github/workflows/fossa.yml, .github/workflows/ossf-scorecard.yml
See https://github.com/open-telemetry/community/issues/2636 and https://github.com/open-telemetry/community/issues/2574 for details.
=> Add standard workflows

pkg/transform/k8s.go, pkg/transform/k8s_test.go
Ports populating the k8skind field from Beyla.
=> Add k8s kind population

pkg/export/attributes/attr_selector.go
This allows for derivatives of OBI to supply custom attribute group definitions
=> Add ability to supply custom attribute selector function

pkg/export/otel/traces.go, pkg/export/otel/traces_test.go
Supersedes https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/85
Original PR: https://github.com/grafana/beyla/pull/1892Original PR: https://github.com/grafana/beyla/pull/1892
=> Port trace fixes from Beyla

pkg/components/ebpf/logger/logger.go
I was originally working on a branch without https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/commit/08d9fca59d9bad25b249bce5acd443a7019f7e40 and I realized later I fixed something already fixed in main; This changes nothing except using a sys/unix function instead of `readString`
=> bpf: use unix.ByteSliceToString for debug logs instead of unsafe

pkg/components/discover/finder.go, pkg/components/discover/matcher.go, pkg/components/discover/matcher_test.go, pkg/components/discover/watcher_kube.go, pkg/components/discover/watcher_kube_test.go, pkg/components/discover/watcher_proc.go, pkg/components/discover/watcher_proc_test.go
This is required for further refactors in Beyla
=> Make ProcessAttrs in watcher_proc.go public

pkg/components/discover/matcher.go
Porting these changes from Beyla.
=> Add extra info on debug logs in matcher.go

pkg/components/pipe/global/context.go, pkg/components/pipe/instrumenter.go, pkg/components/pipe/instrumenter_test.go, pkg/export/otel/common.go, pkg/export/otel/traces.go, pkg/export/otel/traces_test.go
Simplifies the way extra resource attributes can be passed.
=> Cleanup API for extra resource attributes

pkg/components/discover/finder.go
`ProcessFinder.Start` can be invoked from any component or collector that vendors OBI. However, that component might want to override the default behavior or to listen for some internal events.
This PR enables passing a set of `ProcessFinderStartOption`, despite ATM we only provide one, to override the enriched process events queue.
=> Prepares ProcessFinder pipeline for vendoring

pkg/components/imetrics/iprom.go, pkg/export/otel/metrics_internal.go, pkg/export/prom/prom.go, pkg/kubecache/instrument/imetrics.go, test/integration/internals_test.go, test/integration/k8s/informer_cache/k8s_informer_cache_main_test.go, test/integration/multiprocess_test.go, test/integration/red_test.go
Partially addressing https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/issues/282
=> Rename beyla_ prefix to obi_ in internal metrics

bpf/bpfcore/utils.h, bpf/common/common.h, bpf/common/connection_info.h, bpf/generictracer/k_tracer.c, bpf/generictracer/protocol_mysql.h, bpf/generictracer/protocol_postgres.h, bpf/generictracer/protocol_tcp.h, pkg/app/request/span.go, pkg/components/ebpf/common/common.go, pkg/components/ebpf/common/sql_detect_mysql.go, pkg/components/ebpf/common/sql_detect_postgres.go, pkg/components/ebpf/common/tcp_detect_transform.go, pkg/components/ebpf/generictracer/generictracer.go, pkg/components/sqlprune/mysql.go, pkg/components/sqlprune/postgres.go, pkg/components/sqlprune/postgres_test.go, pkg/components/sqlprune/sqlparser.go, pkg/components/sqlprune/sqlparser_test.go, pkg/config/ebpf_tracer.go, pkg/obi/config.go, pkg/obi/config_test.go, test/integration/docker-compose-python-postgresql.yml, test/integration/red_test_python_sql.go
- Classify postgres connections in ebpf
- Add large buffers support for postgres
- Parse postgres errors
=> bpf: classify postgres in ebpf, add large buffers and errors support

README.md
Fixes https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/issues/415
=> docs: fix CONTRIBUTING.md link

pkg/components/helpers/container/container.go, pkg/components/helpers/container/container_test.go
Fixes: https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/issues/481
=> Add other patterns for container ID

generator.Dockerfile
Addresses this comment: https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/513#discussion_r2303977204
=> Add wget to generator.Dockerfile

test/integration/components/kafka/docker-compose.yml, test/oats/kafka/docker-compose-beyla-go-kafka-go.yml, test/oats/kafka/docker-compose-beyla-go-kafka-sarama.yml, test/oats/kafka/docker-compose-beyla-python-kafka.yml
Context: https://cloud-native.slack.com/archives/C08P9L4FPKJ/p1756398343262469
=> tests: use bitnamilegacy instead of bitnami repository

pkg/export/otel/metrics_test.go
This unit test suddenly became very flaky.
After the fix, I've manually retriggered unit tests in this PR and they have passed consistently.
=> Try to fix flaky TestAppMetrics_TracesHostInfo test

test/vm/Makefile
VM tests are now failing with fallocate running out of space. We don't need 20G anyway.
=> Decrease VM disk size

bpf/tctracer/tctracer.c, bpf/tpinjector/tpinjector.c, test/integration/components/gohttp2/client/Dockerfile
This PR fixes some minor typos found in the codebase. These changes don't affect functionality.
=> Correct some typos in the code
